In [1]:
import pandas as pd

In [2]:
climer_data = pd.read_csv("/private/home/arjunrs1/CliMer/data/egoexo4d/egoexo4d_all_views_keysteps_train.csv")
ks_data = pd.read_csv("/private/home/arjunrs1/exo_narration_grounding/data_processing/time_interval_annotation_files/keystep_annotations/train.csv")

In [3]:
# Function to extract take_uid from video_id
def extract_take_uid(video_id):
    rsplit_idx = 2 if "aria" in video_id else 1
    return video_id.rsplit('_', rsplit_idx)[0]
# Apply the function to extract take_uid
climer_data['take_uid'] = climer_data['video_id'].apply(extract_take_uid)
# Ensure data types match
climer_data['narration_frame'] = climer_data['narration_frame'].astype(int)
ks_data['narration_frame'] = ks_data['narration_frame'].astype(int)
# Strip whitespace and ensure case consistency
climer_data['take_uid'] = climer_data['take_uid'].str.strip().str.lower()
ks_data['take_uid'] = ks_data['take_uid'].str.strip().str.lower()
# Merge with indicator
merged_data = pd.merge(climer_data, ks_data, on=['narration_frame', 'take_uid'], how='inner', suffixes=('', '_y'), indicator=True)
# Filter to keep only rows that were successfully merged
climer_data_filtered = merged_data[merged_data['_merge'] == 'both'].drop(columns=['_merge'])
# Select the relevant columns
result = climer_data_filtered[['clip_id', 'unique_narration_id']]
print(result)

                                    clip_id         unique_narration_id
0                      cmu_bike01_2_cam01_0           cmu_bike01_2_ks_0
1                      cmu_bike01_2_cam01_1           cmu_bike01_2_ks_1
2                      cmu_bike01_2_cam02_0           cmu_bike01_2_ks_0
3                      cmu_bike01_2_cam02_1           cmu_bike01_2_ks_1
4                      cmu_bike01_2_cam03_0           cmu_bike01_2_ks_0
...                                     ...                         ...
60820  utokyo_pcr_2001_38_6_aria01_214-1_30  utokyo_pcr_2001_38_6_ks_30
60821  utokyo_pcr_2001_38_6_aria01_214-1_31  utokyo_pcr_2001_38_6_ks_31
60822  utokyo_pcr_2001_38_6_aria01_214-1_32  utokyo_pcr_2001_38_6_ks_32
60823  utokyo_pcr_2001_38_6_aria01_214-1_33  utokyo_pcr_2001_38_6_ks_33
60824  utokyo_pcr_2001_38_6_aria01_214-1_34  utokyo_pcr_2001_38_6_ks_34

[60825 rows x 2 columns]

In [4]:
result

                                    clip_id         unique_narration_id
0                      cmu_bike01_2_cam01_0           cmu_bike01_2_ks_0
1                      cmu_bike01_2_cam01_1           cmu_bike01_2_ks_1
2                      cmu_bike01_2_cam02_0           cmu_bike01_2_ks_0
3                      cmu_bike01_2_cam02_1           cmu_bike01_2_ks_1
4                      cmu_bike01_2_cam03_0           cmu_bike01_2_ks_0
...                                     ...                         ...
60820  utokyo_pcr_2001_38_6_aria01_214-1_30  utokyo_pcr_2001_38_6_ks_30
60821  utokyo_pcr_2001_38_6_aria01_214-1_31  utokyo_pcr_2001_38_6_ks_31
60822  utokyo_pcr_2001_38_6_aria01_214-1_32  utokyo_pcr_2001_38_6_ks_32
60823  utokyo_pcr_2001_38_6_aria01_214-1_33  utokyo_pcr_2001_38_6_ks_33
60824  utokyo_pcr_2001_38_6_aria01_214-1_34  utokyo_pcr_2001_38_6_ks_34

[60825 rows x 2 columns]

In [5]:
"utokyo_pcr_2001_38_6_ks_34".split("_ks")[0]

'utokyo_pcr_2001_38_6'

In [8]:
climer_data_filtered.head()

,video_id,duration,narration_frame,narration,verb_class,noun_class,clip_id,take_uid,narration_y,start_frame,end_frame,ego_camera_path,duration_sec,unique_narration_id
0,cmu_bike01_2_cam01,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam01_0,cmu_bike01_2,get the wrench from the table,2247,2339,frame_aligned_videos/aria01_214-1.mp4,110.933333,cmu_bike01_2_ks_0
1,cmu_bike01_2_cam01,110.933333,2731,loosen the axle nuts on both sides to remove t...,"['loosen', 'remove']","['axle', 'nuts', 'sides', 'wheel']",cmu_bike01_2_cam01_1,cmu_bike01_2,loosen the axle nuts on both sides to remove t...,2340,3122,frame_aligned_videos/aria01_214-1.mp4,110.933333,cmu_bike01_2_ks_1
2,cmu_bike01_2_cam02,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam02_0,cmu_bike01_2,get the wrench from the table,2247,2339,frame_aligned_videos/aria01_214-1.mp4,110.933333,cmu_bike01_2_ks_0
3,cmu_bike01_2_cam02,110.933333,2731,loosen the axle nuts on both sides to remove t...,"['loosen', 'remove']","['axle', 'nuts', 'sides', 'wheel']",cmu_bike01_2_cam02_1,cmu_bike01_2,loosen the axle nuts on both sides to remove t...,2340,3122,frame_aligned_videos/aria01_214-1.mp4,110.933333,cmu_bike01_2_ks_1
4,cmu_bike01_2_cam03,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam03_0,cmu_bike01_2,get the wrench from the table,2247,2339,frame_aligned_videos/aria01_214-1.mp4,110.933333,cmu_bike01_2_ks_0

In [7]:
climer_data.head()

,video_id,duration,narration_frame,narration,verb_class,noun_class,clip_id,take_uid
0,cmu_bike01_2_cam01,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam01_0,cmu_bike01_2
1,cmu_bike01_2_cam01,110.933333,2731,loosen the axle nuts on both sides to remove t...,"['loosen', 'remove']","['axle', 'nuts', 'sides', 'wheel']",cmu_bike01_2_cam01_1,cmu_bike01_2
2,cmu_bike01_2_cam02,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam02_0,cmu_bike01_2
3,cmu_bike01_2_cam02,110.933333,2731,loosen the axle nuts on both sides to remove t...,"['loosen', 'remove']","['axle', 'nuts', 'sides', 'wheel']",cmu_bike01_2_cam02_1,cmu_bike01_2
4,cmu_bike01_2_cam03,110.933333,2293,get the wrench from the table,['get'],"['wrench', 'table']",cmu_bike01_2_cam03_0,cmu_bike01_2